export interface Song {
  id: number
  title: string
  singer: string
  voice: string
  language: 'japanese' | 'chinese' | 'other'
  producer: string
  link: string
  chorusStart: number
  chorusEnd: number
}

/* eslint-disable autocorrect/issue */
export const SONGS: Song[] = [
  {
    id: 1,
    title: '私のドッペルゲンガー',
    singer: '可不',
    voice: '可不',
    producer: 'DIVELA',
    language: 'japanese',
    link: 'https://www.bilibili.com/video/BV1ev411E7Kv',
    chorusStart: 35,
    chorusEnd: 55,
  },
  {
    id: 2,
    title: 'テトリス',
    singer: '重音テト',
    voice: '重音テト',
    language: 'japanese',
    producer: '柊マグネタイト',
    link: 'https://www.bilibili.com/video/BV1GADYYmEnd',
    chorusStart: 40,
    chorusEnd: 62,
  },
  {
    id: 3,
    title: 'のじゃロリック',
    singer: '桃寝ちのい, ちょこ',
    voice: '桃寝ちのい, ちょこ',
    language: 'japanese',
    producer: 'なみぐる',
    link: 'https://www.bilibili.com/video/BV1kH4y1c7WY',
    chorusStart: 62,
    chorusEnd: 86,
  },
  {
    id: 4,
    title: 'ロストワンの号哭',
    singer: '鏡音リン',
    voice: '鏡音リン',
    language: 'japanese',
    producer: 'Neru',
    link: 'https://www.bilibili.com/video/BV1Nq4y1673B',
    chorusStart: 76,
    chorusEnd: 100,
  },
  {
    id: 5,
    title: '苍蝇',
    singer: '赤羽',
    voice: '赤羽',
    language: 'chinese',
    producer: 'ilem',
    link: 'https://www.bilibili.com/video/BV1p5411879s',
    chorusStart: 44,
    chorusEnd: 54,
  },
  {
    id: 6,
    title: '冠世一战',
    singer: '言和',
    voice: '言和 V5',
    language: 'chinese',
    producer: 'Litterzy, 墨大筝, Creuzer, CuTTleFiSh',
    link: 'https://www.bilibili.com/video/BV17t411y7D2',
    chorusStart: 2,
    chorusEnd: 23,
  },
  {
    id: 7,
    title: 'おどりゃんせ',
    singer: '初音ミク, GUMI',
    voice: '初音ミク, GUMI',
    language: 'japanese',
    producer: 'ユリイ・カノン',
    link: 'https://www.bilibili.com/video/BV1L1h9zgEeg',
    chorusStart: 70,
    chorusEnd: 92,
  },
  {
    id: 8,
    title: '失敗作少女',
    singer: '初音ミク',
    voice: '初音ミク',
    language: 'japanese',
    producer: 'かいりきベア',
    link: 'https://www.bilibili.com/video/BV1X4411Q7m2',
    chorusStart: 45,
    chorusEnd: 61,
  },
  {
    id: 9,
    title: '代替我',
    singer: '洛天依',
    voice: '洛天依 V5/AI',
    language: 'chinese',
    producer: 'Chasel懿辰',
    link: 'https://www.bilibili.com/video/BV1Eh4y1V7Kd',
    chorusStart: 39,
    chorusEnd: 67,
  },
  {
    id: 10,
    title: '裏表ラバーズ',
    singer: '初音ミク',
    voice: '初音ミク',
    language: 'japanese',
    producer: 'wowaka',
    link: 'https://www.bilibili.com/video/BV1xx411c7Rj',
    chorusStart: 57,
    chorusEnd: 94,
  },
  {
    id: 11,
    title: 'バグ',
    singer: '初音ミク',
    voice: '初音ミク',
    language: 'japanese',
    producer: 'かいりきベア',
    link: 'https://www.bilibili.com/video/BV1n94y117jB',
    chorusStart: 47,
    chorusEnd: 69,
  },
  {
    id: 12,
    title: '夜鹭',
    singer: '言和',
    voice: '言和 AI',
    language: 'chinese',
    producer: 'Licis, 闪光舞姬神猫, 鬼面P, 闪光舞姬神猫',
    link: 'https://www.bilibili.com/video/BV1Gs4y1r7V4',
    chorusStart: 52,
    chorusEnd: 78,
  },
  {
    id: 13,
    title: 'おべんきょうたいむ',
    singer: '足立レイ',
    voice: '足立レイ',
    language: 'japanese',
    producer: 'litmus*',
    link: 'https://www.bilibili.com/video/BV1DRzJYLEmB',
    chorusStart: 53,
    chorusEnd: 75,
  },
  {
    id: 14,
    title: 'きゅうくらりん',
    singer: '可不',
    voice: '可不',
    language: 'japanese',
    producer: 'いよわ',
    link: 'https://www.bilibili.com/video/BV1MQ4y1a7JY',
    chorusStart: 49,
    chorusEnd: 65,
  },
  {
    id: 15,
    title: 'Telecaster B-boy',
    singer: '鏡音レン',
    voice: '鏡音レン',
    language: 'japanese',
    producer: 'すりぃ',
    link: 'https://www.bilibili.com/video/BV12K411K7Gr',
    chorusStart: 38,
    chorusEnd: 59,
  },
  {
    id: 16,
    title: '小阳春',
    singer: '言和',
    voice: '言和 V5',
    language: 'chinese',
    producer: '负二价-, 白昼梦',
    link: 'https://www.bilibili.com/video/BV1e3411E7b1',
    chorusStart: 53,
    chorusEnd: 83,
  },
  {
    id: 17,
    title: '得过且过的勇者',
    singer: '言和, 洛天依',
    voice: '言和 V3, 洛天依',
    language: 'chinese',
    producer: 'ilem',
    link: 'https://www.bilibili.com/video/BV1Zb411j7vb',
    chorusStart: 59,
    chorusEnd: 77,
  },
  {
    id: 18,
    title: 'Freak Out Hr.',
    singer: 'POPY, ROSE',
    voice: 'POPY, ROSE',
    language: 'japanese',
    producer: '雄之助',
    link: 'https://www.bilibili.com/video/BV1hk4y1x7hb',
    chorusStart: 43,
    chorusEnd: 65,
  },
  {
    id: 19,
    title: '最佳赏味期',
    singer: '言和',
    voice: '言和 AI',
    language: 'chinese',
    producer: '纪远, bobo, 坐标p',
    link: 'https://www.bilibili.com/video/BV1UP411o79v',
    chorusStart: 60,
    chorusEnd: 80,
  },
  {
    id: 20,
    title: '霜雪千年',
    singer: '洛天依, 乐正绫',
    voice: '洛天依 V3, 乐正绫 V3',
    language: 'chinese',
    producer: 'COPY',
    link: 'https://www.bilibili.com/video/BV1zM4m1r7JS',
    chorusStart: 55,
    chorusEnd: 86,
  },
  {
    id: 21,
    title: 'ハナタバ',
    singer: '可不',
    voice: '可不',
    language: 'japanese',
    producer: 'MIMI',
    link: 'https://www.bilibili.com/video/BV1VPcrzREby',
    chorusStart: 40,
    chorusEnd: 57,
  },
  {
    id: 22,
    title: '世末歌者',
    singer: '乐正绫',
    voice: '乐正绫 V3',
    language: 'chinese',
    producer: 'COPY',
    link: 'https://www.bilibili.com/video/BV1Qs411k7Qv',
    chorusStart: 84,
    chorusEnd: 105,
  },
  {
    id: 23,
    title: '星界ちゃんと可不ちゃんのおつかい合騒曲',
    singer: '星界, 可不',
    voice: '星界, 可不',
    language: 'japanese',
    producer: '南ノ南',
    link: 'https://www.bilibili.com/video/BV12Y4y1U7Kh',
    chorusStart: 50,
    chorusEnd: 68,
  },
  {
    id: 24,
    title: 'だれかの心臓になれたなら',
    singer: 'GUMI',
    voice: 'GUMI',
    language: 'japanese',
    producer: 'ユリイ・カノン',
    link: 'https://www.bilibili.com/video/BV1njnFzNEwp',
    chorusStart: 68,
    chorusEnd: 94,
  },
  {
    id: 25,
    title: 'Attack！',
    singer: '洛天依, 言和, 乐正绫, 乐正龙牙, 徵羽摩柯, 墨清弦',
    voice: '洛天依, 言和, 乐正绫, 乐正龙牙, 徵羽摩柯, 墨清弦',
    language: 'chinese',
    producer: '人形兎, 冥凰, Bitman, 动点P, Creuzer',
    link: 'https://www.bilibili.com/video/BV1m4411M7iy',
    chorusStart: 79,
    chorusEnd: 91,
  },
  {
    id: 26,
    title: '雪降り ~雪が降っている~',
    singer: '結月ゆかり',
    voice: '結月ゆかり',
    language: 'japanese',
    producer: 'AiSS / NE1516Hz',
    link: 'https://www.bilibili.com/video/BV1D66hY7E1C',
    chorusStart: 63,
    chorusEnd: 88,
  },
  {
    id: 27,
    title: '白鸟过河滩',
    singer: '洛天依',
    voice: '洛天依 V5',
    language: 'chinese',
    producer: 'ilem',
    link: 'https://www.bilibili.com/video/BV1wT4y1k7Pw',
    chorusStart: 52,
    chorusEnd: 90,
  },
  {
    id: 28,
    title: '听我一言',
    singer: '言和',
    voice: '言和 AI',
    language: 'chinese',
    producer: 'iKz_茶壶, 邪叫教主, Creuzer',
    link: 'https://www.bilibili.com/video/BV11h4y1Z76C',
    chorusStart: 6,
    chorusEnd: 32,
  },
  {
    id: 29,
    title: 'おくすり飲んで寝よう',
    singer: '初音ミク',
    voice: '初音ミク',
    language: 'japanese',
    producer: 'もちうつね',
    link: 'https://www.bilibili.com/video/BV1Le4y1n7jj',
    chorusStart: 58,
    chorusEnd: 92,
  },
  {
    id: 30,
    title: '上上签',
    singer: '言和',
    voice: '言和 AI',
    language: 'chinese',
    producer: '瞳荧, 顾念之, papaw泡泡, 郑射虎, 烂兔子',
    link: 'https://www.bilibili.com/video/BV1fM4y1j7Wv',
    chorusStart: 59,
    chorusEnd: 84,
  },
  {
    id: 31,
    title: 'ウミユリ海底譚',
    singer: '初音ミク',
    voice: '初音ミク',
    language: 'japanese',
    producer: 'n-buna',
    link: 'https://www.bilibili.com/video/BV1zW411P7Yh',
    chorusStart: 63,
    chorusEnd: 78,
  },
  {
    id: 32,
    title: '灼之花',
    singer: '洛天依, 乐正绫',
    voice: '洛天依 V3, 乐正绫 V3',
    language: 'chinese',
    producer: 'COPY',
    link: 'https://www.bilibili.com/video/BV1ps411X7QG',
    chorusStart: 91,
    chorusEnd: 108,
  },
  {
    id: 33,
    title: '造花の道、歩めば',
    singer: '可不',
    voice: '可不',
    language: 'japanese',
    producer: 'South&',
    link: 'https://www.bilibili.com/video/BV14fApekEPn',
    chorusStart: 63,
    chorusEnd: 95,
  },
  {
    id: 34,
    title: 'ちっちゃな私',
    singer: '重音テト',
    voice: '重音テト',
    language: 'japanese',
    producer: 'マサラダ',
    link: 'https://www.bilibili.com/video/BV148tzzVEoK',
    chorusStart: 44,
    chorusEnd: 57,
  },
  {
    id: 35,
    title: '在下，言和',
    singer: '言和',
    voice: '言和 V5',
    language: 'chinese',
    producer: 'iKz_茶壶, Creuzer, 海纳不是法号, AYWC八毛',
    link: 'https://www.bilibili.com/video/BV1xU4y1q79a',
    chorusStart: 86,
    chorusEnd: 100,
  },
  {
    id: 36,
    title: '梦之雨',
    singer: '言和',
    voice: '言和 V3',
    language: 'chinese',
    producer: '霜玉冻牛丸, Dr.Yun, GhostFinal',
    link: 'https://www.bilibili.com/video/BV1HE411b7Hf',
    chorusStart: 60,
    chorusEnd: 101,
  },
  {
    id: 37,
    title: '我们停止歌唱的理由',
    singer: '言和',
    voice: '言和 AI',
    language: 'chinese',
    producer: 'Licis, 莫米兔',
    link: 'https://www.bilibili.com/video/BV1mW421R7EV',
    chorusStart: 58,
    chorusEnd: 75,
  },
  {
    id: 38,
    title: '瓶中对决',
    singer: '言和',
    voice: '言和 AI',
    language: 'chinese',
    producer: 'JUSF周存',
    link: 'https://www.bilibili.com/video/BV11u4y1S7kq',
    chorusStart: 41,
    chorusEnd: 56,
  },
  {
    id: 39,
    title: '东京不太热',
    singer: '洛天依',
    voice: '洛天依 V4',
    language: 'chinese',
    producer: 'Z新豪',
    link: 'https://www.bilibili.com/video/BV17s411D731',
    chorusStart: 55,
    chorusEnd: 69,
  },
  {
    id: 40,
    title: 'Everlasting/永续',
    singer: '洛天依, 言和, 乐正绫, 乐正龙牙, 徵羽摩柯, 墨清弦',
    voice: '洛天依, 言和, 乐正绫, 乐正龙牙, 徵羽摩柯, 墨清弦',
    language: 'chinese',
    producer: 'Licis, 莫米兔, 奶茶墨诺',
    link: 'https://www.bilibili.com/video/BV1uzmbYdE5e',
    chorusStart: 53,
    chorusEnd: 74,
  },
  {
    id: 41,
    title: '1000年生きてる',
    singer: '初音ミク',
    voice: '初音ミク',
    language: 'japanese',
    producer: 'もちうつね',
    link: 'https://www.bilibili.com/video/BV1Ua4y1W7rV',
    chorusStart: 51,
    chorusEnd: 70,
  },
  {
    id: 42,
    title: 'KING',
    singer: 'GUMI',
    voice: 'GUMI',
    producer: 'Kanaria',
    language: 'other',
    link: 'https://www.bilibili.com/video/BV1Ya4y1E7pk',
    chorusStart: 53,
    chorusEnd: 65,
  },
  {
    id: 43,
    title: 'ぼかろころしあむ',
    singer: '鏡音リン',
    voice: '鏡音リン',
    language: 'japanese',
    producer: 'DIVELA',
    link: 'https://www.bilibili.com/video/BV1Vr4y1F7JS',
    chorusStart: 49,
    chorusEnd: 79,
  },
  {
    id: 44,
    title: '你好，世界',
    singer: '徵羽摩柯',
    voice: '徵羽摩柯',
    language: 'chinese',
    producer: 'OQQ_, 正弦函数p, 鸣泣的紫蝶',
    link: 'https://www.bilibili.com/video/BV1ss411377E',
    chorusStart: 57,
    chorusEnd: 84,
  },
  {
    id: 45,
    title: '世末积雨云',
    singer: '洛天依',
    voice: '洛天依 V3',
    language: 'chinese',
    producer: 'COPY',
    link: 'https://www.bilibili.com/video/BV1Mx411P75Y',
    chorusStart: 69,
    chorusEnd: 113,
  },
  {
    id: 46,
    title: '四面楚歌',
    singer: '徵羽摩柯',
    voice: '徵羽摩柯',
    language: 'chinese',
    producer: '粽子粥, 一碗热汤, Kevinz, 哈士奇p, Digifan',
    link: 'https://www.bilibili.com/video/BV1WW4y1M71C',
    chorusStart: 43,
    chorusEnd: 68,
  },
];
/* eslint-enable autocorrect/issue */

export const LANGUAGE_LABELS = {
  japanese: '日语',
  chinese: '中文',
  other: '其他',
} as const;

export const LANGUAGE_COLORS = {
  japanese: 'error',
  chinese: 'success',
  other: 'info',
} as const;

export function getRandomSongs(count = 20): Song[] {
  const shuffled = [...SONGS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
